config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: proc { |env| [200, {}, [File.read("{Rails.root}/public/index.html")]] }

  # Log in
  get "/auth/login", to: "sessions#new"
  post "/auth/login", to: "sessions#create"

  # Log out
  delete "/auth/logout", to: "sessions#destroy"
  
  # USER ROUTES
  get "/register", to: "users#new"
  post "/register", to: "users#create"
  #
  # # DECKS ROUTES
  # # Get all decks of a particular user
  # get "/decks", to: "decks#index"
  #
  # # Get a particular deck
  # get "/decks/:id", to: "decks#show"
  #
  # # Create a new deck
  # get "/decks/new", to: "decks#new"
  # post "/decks", to: "decks#create"
  #
  # # Edit a deck
  # get "/decks/:id/edit", to: "decks#edit"
  # patch "/decks/:id", to: "decks#update"
  #
  #
  #
  #
  # # CARDS ROUTES
  # # Show all cards in a deck
  # get "/decks/:id/cards", to: "cards#index"
  #
  # # Show a particular card
  # get "/decks/:id/cards/:id", to: "cards#show"
  #
  # # Create a new card
  # get "/decks/:id/cards/new", to: "cards#new"
  # post "/decks/:id/cards", to: "cards#create"
  #
  # # Edit a card
  # get "/decks/:id/cards/:id/edit", to: "cards#edit"
  # patch "/decks/:id/cards/:id", to: "cards#update"
  #
  # # Delete a card
  # delete "/decks/:id/cards/:id", to: "cards#destroy"

  resources :users, except: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :decks, except: [:destroy] do
      resources :cards
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[ show edit update destroy ]

  # GET /cards or /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1 or /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards or /cards.json
  def create
    @card = Card.new(card_params)
    puts @card
    respond_to do |format|
      if @card.save
        @deck.card_count += 1
        format.html { redirect_to user_decks_path(@card), notice: "Card was successfully created." }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to card_url(@card), notice: "Card was successfully updated." }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, notice: "Card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:question, :answer, :deck_id)
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[ show edit update destroy ]

  # GET /decks or /decks.json
  def index
    @decks = Deck.where(user_id: params[:user_id]).all
  end

  # GET /decks/1 or /decks/1.json
  def show
    @deck = Deck.where(user_id: params[:user_id], id: params[:id]).first
  end

  # GET /decks/new
  def new
    @deck = Deck.create
  end

  # GET /decks/1/edit
  def edit

  end

  # POST /decks or /decks.json
  def create
    d_params = deck_params
    d_params[:card_count] = 0
    d_params[:user_id] = @current_user
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to user_decks_url, notice: "Deck was successfully created." }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1 or /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to user_decks_url(@deck), notice: "Deck was successfully updated." }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1 or /decks/1.json
  def destroy
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to user_decks_url, notice: "Deck was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deck_params
      params.require(:deck).permit(:topic, :card_count, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # renders the login view
  def new
    @session_request = SessionRequest.new
  end

  def create
    @session_request = SessionRequest.new(session_request_params)
    if @user = @session_request.authenticate
      session[:user_id] = @user.id
      redirect_to user_decks_path(@user)
    else
      render :new, status: :unauthorized
    end
  end

  def destroy
    session[:user_id] = nil
  end

  private
  def session_request_params
    params.require(:session_request).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password_digest, :email, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id card %>">
  <p>
    <strong>Question:</strong>
    <%= card.question %>
  </p>

  <p>
    <strong>Answer:</strong>
    <%= card.answer %>
  </p>

  <p>
    <strong>Deck:</strong>
    <%= card.deck_id %>
  </p>

</div>

app/views/cards/_form.html.erb
<%= form_with(model: Card) do |form| %>
  <% if card.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.label :answer, style: "display: block" %>
    <%= form.text_field :answer %>
  </div>

  <div>
    <%= form.label :deck_id, style: "display: block" %>
    <%= form.text_field :deck_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render "form", card: @card %>

<br>

<div>
  <%= link_to "Show this card", @card %> |
  <%= link_to "Back to cards", cards_path %>
</div>

app/views/cards/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cards</h1>

<div id="cards">
  <% @cards.each do |card| %>
    <%= render card %>
    <p>
      <%= link_to "Back to user decks", user_decks_url %>
    </p>
  <% end %>
</div>

<%= link_to "New card", new_user_deck_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= form_with model: @card, url: user_deck_cards_path, method: :post do |form| %>
  <div>
    <%= form.label :question %>
    <%= form.text_field :question %>
    <br/>
  </div>
  <div>
    <%= form.label :answer %>
    <%= form.text_field :answer %>
    <br/>
  </div>
  <div>
    <%= form.submit "Create card" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to cards", user_deck_cards_path %>
</div>

app/views/cards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @card %>

<div>
  <%= link_to "Edit this card", edit_card_path(@card) %> |
  <%= link_to "Back to cards", cards_path %>

  <%= button_to "Destroy this card", @card, method: :delete %>
</div>

app/views/decks/_deck.html.erb
<div id="<%= dom_id deck %>">
  <p>
    <h2><strong>Topic:</strong></h2>
    <strong><%= deck.topic %></strong>
  </p>

  <p>
    <strong>Card count:</strong>
    <%= deck.card_count %>
  </p>

  <p>
    <strong>User:</strong>
    <%= deck.user_id %>
  </p>

</div>

app/views/decks/_form.html.erb
<%= form_with(model: deck) do |form| %>
  <% if deck.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
        <% deck.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :topic, style: "display: block" %>
    <%= form.text_field :topic %>
  </div>

  <div>
    <%= form.label :card_count, style: "display: block" %>
    <%= form.number_field :card_count %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render "form", deck: @deck %>

<br>

<div>
  <%= link_to "Show this deck", @deck %> |
  <%= link_to "Back to decks", decks_path %>
</div>

app/views/decks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Decks</h1>

<div id="decks">
  <% @decks.each do |deck| %>
    <%= render deck %> <br/>
  <% end %>
</div>

<%= link_to "New deck", new_user_deck_path %>
<%= link_to "Log out", auth_login_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%#= render "form", deck: @deck %>

<br>

<div>
  <%= form_with model: @deck, url: user_decks_url do |form| %>
    <div>
      <%= form.label :topic %><br/>
      <%= form.text_field :topic %>
    </div>
    <div>
      <%= form.submit "Create deck" %>
    </div>
  <% end %>
  <br/>
  <%= link_to "Back to decks", user_decks_path %>
</div>

app/views/decks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render 'cards/card' %>

<div>
  <%= link_to "Edit this deck", edit_deck_path(@deck) %> |
  <%= link_to "Back to decks", decks_path %>

  <%= button_to "Destroy this deck", @deck, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorFlashcards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>